HenTube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('Users.urls')),
    path('channels/', include('Channels.urls')),
    path('videos/', include('Videos.urls')),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Videos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:video_id>/', views.video, name='video'),
    path('upload_video/', views.upload_video, name='upload_video'),
    path('set_comment/', views.create_comment, name='set_comment'),
    path('react/', views.react, name='react'),
]

app_name = 'Videos'

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main_page, name='main'),
]

app_name = 'main'

Videos/models.py
from django.db import models
from Channels.models import Channels
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User


class VideoTags(models.Model):
    value = models.TextField(max_length=20)


def videos_upload_path(instance, filename):
    return 'videos/user_{0}/{1}'.format(instance.publisher.id, filename)


def previews_upload_path(instance, filename):
    return 'previews/user_{0}/{1}'.format(instance.publisher.id, filename)


class Videos(models.Model):
    publisher = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    title = models.TextField(max_length=64)
    description = models.TextField(max_length=500, default='n/n')
    # duration = models.IntegerField(default=0)
    pub_date = models.DateTimeField("publication date", default=timezone.now())
    video_path = models.FileField(
        upload_to=videos_upload_path,
        validators=[FileExtensionValidator(allowed_extensions=['mp4'])]
    )
    preview_path = models.ImageField(
        upload_to=previews_upload_path,
        default='previews/base_preview.jpg'
    )
    views = models.BigIntegerField(default=0)
    tags = models.ManyToManyField(VideoTags, null=True)

    def get_likes(self):
        return self.reactions.filter(video_id=self.id, value=True).count()

    def get_dislikes(self):
        return self.reactions.filter(video_id=self.id, value=False).count()

    def get_comments(self):
        return self.comments.filter(video_id=self.id).order_by('-pub_date')

    def views_per_day(self):
        pass

    def likes_per_day(self):
        pass

    def dislikes_per_day(self):
        pass

    def comments_per_day(self):
        pass


class Reactions(models.Model):
    author = models.ForeignKey(
        Channels,
        on_delete=models.CASCADE,
        related_name='reactions'
    )
    video = models.ForeignKey(
        Videos,
        on_delete=models.CASCADE,
        related_name='reactions'
    )
    value = models.BooleanField()
    pub_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'video_id: {self.video_id}, author_id: {self.author_id}, value: {self.value}, date: {self.pub_date}'


class Comments(models.Model):
    author = models.ForeignKey(
        Channels,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    video = models.ForeignKey(
        Videos,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    value = models.TextField()
    pub_date = models.DateTimeField(default=timezone.now)

Videos/forms.py
from django import forms


class UploadVideoForm(forms.Form):
    title = forms.CharField(label='Title', max_length=32)
    video = forms.FileField(label='Video')
    preview = forms.ImageField(label='Preview')

    # def __str__(self):
    #     return f'title {self.title}'


class AddCommentForm(forms.Form):
    value = forms.CharField(max_length=300)
    video_id = forms.IntegerField()
    author_id = forms.IntegerField()

Videos/views.py
from django.shortcuts import render
from django.http import JsonResponse
from datetime import datetime
from django.contrib.auth.decorators import login_required
from .forms import UploadVideoForm, AddCommentForm
from .models import Videos, Reactions, Comments
import sqlite3


con = sqlite3.connect('../db.sqlite3', check_same_thread=False)
cur = con.cursor()


def video(request, video_id):
    v = Videos.objects.get(pk=video_id)
    likes = v.get_likes()
    dislikes = v.get_dislikes()
    comments = v.get_comments()[:20]
    return render(request, 'Videos/Index.html', {'video': v, 'likes': likes,
                                                 'dislikes': dislikes, 'comments': comments,
                                                 })


@login_required(login_url='Users:login')
def upload_video(request):
    if request.method == 'POST':
        form = UploadVideoForm(request.POST, request.FILES)
        if form.is_valid():
            new_video = request.FILES['video']
            new_preview = request.FILES['preview']
            safe_name = datetime.now().strftime("%Y_%m_%d_%H_%M_%S")
            new_video.name = safe_name
            new_preview.name = safe_name + '.' + new_preview.name.split('.')[-1]
            Videos(
                title=form.cleaned_data['title'],
                video_path=new_video,
                preview_path=new_preview,
                publisher=request.user,
            ).save()
    form = UploadVideoForm()
    return render(request, 'Videos/upload_video.html', {'UploadVideoForm': form})


@login_required(login_url='Users:login')
def react(request):
    value = True if request.POST['value'] == 'like' else False
    video = Videos.objects.get(pk=request.POST['video_id'])
    record = Reactions.objects.filter(
        video_id=request.POST['video_id'],
        author_id=request.POST['author_id'],
    ).first()
    if record and record.value is value:
        record.delete()
    elif record and record.value is not value:
        record.value = value
        record.save()
    else:
        new_record = Reactions(
            video_id=request.POST['video_id'],
            author_id=request.POST['author_id'],
            value=value
        )
        new_record.save()
    likes = video.get_likes()
    dislikes = video.get_dislikes()
    return JsonResponse({'likes': likes, 'dislikes': dislikes}, status=200)


@login_required(login_url='Users:login')
def create_comment(request):
    form = AddCommentForm(request.POST, request.FILES)
    if form.is_valid():
        comment = Comments(
            author_id=request.POST['author_id'],
            video_id=request.POST['video_id'],
            value=request.POST['value'],
        )
        comment.save()
        return JsonResponse({'status': 200, 'value': comment.value, 'username': comment.author.user.username}, status=200)
    return JsonResponse({'status': 500}, status=500)

templates/Videos/Index.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block meta %}
    <title>Video Page</title>
    <link href="{% static '/Videos/css/index.css' %}" rel="stylesheet" type="text/css">
{% endblock meta %}

{% block styles %}
{% endblock styles %}

{% block body %}
<div class="content">
    <div class="video-container">
        <video controls preload="auto" autoplay muted>
            <source src="{% get_media_prefix %}{{ video.video_path }}" type="video/mp4">
        </video>
    </div>
    <div class="meta-video">
        <button id="True" class="False" onclick="Like({{ video.id }}, {{ request.user.id }}, 'like')">Like</button>
        <div class="likes">{{ likes }}</div>
        <button id="False" class="False" onclick="Like({{ video.id }}, {{ request.user.id }}, 'dislike')">DisLike</button>
        <div class="dislikes" onclick="">{{ dislikes }}</div>
        {% if video.creater_id == request.user.id %}
            <div>
                <form class="delete_video_form" method="post" action="{% url 'Videos:delete' %}">
                    {% csrf_token %}
                    <input type="hidden" value="{{ video.id }}" name="video_id">
                    <button type="submit">Delete</button>
                </form>
            </div>
        {% endif %}
    </div>
</div>
<div class="comments-container">
    <div class="create-comment-container">
        <form class="create-comment">
            {% csrf_token %}
            <label>
                Value
                <input type="text" class="comment-value" id="comment-input" name="value">
            </label>
            <input type="hidden" name="author_id" value="{{ request.user.id }}">
            <input type="hidden" name="video_id" value="{{ video.id }}">
            <button type="submit" id="create-comment">Submit</button>
        </form>
    </div>
    <div class="comments">
        {% for i in comments %}
            <div class="comment">
                <div class="user">{{ i.author.user.username }} <span>{{ i.pub_date|naturaltime }}</span></div>
                <div class="value">{{ i.value }}</div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock body %}
{% block scripts %}
    <script type="text/javascript" src="{% static 'js/jquery-3.6.0.min.js' %}" ></script>
    <script type="text/javascript">
    function Like(video_id, author_id, value){
        $.ajax({
            url: "{% url 'Videos:react' %}",
            data: {
                'video_id': video_id,
                'author_id': author_id,
                'value': value,
                'csrfmiddlewaretoken': "{{ csrf_token }}"
            },
            type: 'POST',
            success: function (response){
                $('.likes').text(response.likes)
                $('.dislikes').text(response.dislikes)
            }
        })
        return false;
    }
    </script>
    <script type="text/javascript">
    $(document).ready(function(){
        $('#create-comment').click(function () {
            var data = $('.create-comment').serialize();
            $.ajax({
                url: "{% url 'Videos:set_comment' %}",
                data: data,
                type: 'POST',
                success: function (response){
                    if(response.status === 200){
                        var comment = "<div class=\"comment\"><div class=\"user\">" + response.username + "</div><div class=\"value\">" + response.value + "</div></div>"
                        $('.comments').prepend(comment);
                        $("#comment-input").val(null)
                    }
                    else {
                        alert("ERROR")
                    }
                }
            });
            return false;
        });
    });
    </script>
{% endblock scripts %}

templates/Videos/upload_video.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title></title>
{% endblock meta %}

{% block styles %}
{% endblock styles %}

{% block body %}
<h1>Video upload page</h1>
<div>
    <form method="post" enctype="multipart/form-data" action={% url 'Videos:upload_video' %}>
        {% csrf_token %}
        {{ UploadVideoForm }}
        <button type="submit" class="btn btn-primary">submit</button>
    </form>
</div>
{% endblock body %}