Channels/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:channel_id>/', views.channel, name="Channel"),
    path('subscribe/', views.subscribe, name="Subscribe"),
]

app_name = 'Channels'

HenTube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('Users.urls')),
    path('channels/', include('Channels.urls')),
    path('videos/', include('Videos.urls')),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('registration/', views.registration, name='registration'),
]

app_name = 'Users'

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main_page, name='main'),
]

app_name = 'main'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <style>
        body{
            width: 90%;
            margin: 0 auto;
        }
    </style>
    {% block styles %} {% endblock styles %}
    {% block meta %} {% endblock meta %}
</head>

<body>
<header class="p-3 mb-3 border-bottom">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        {#            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">#}
        {#              <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>#}
        {#            </a>#}

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-0 justify-content-center mb-md-0">
            <li><a href="{% url 'main:main' %}" class="nav-link px-2 link-secondary">Main Page</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
            <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
        </form>

        <ul class="nav col-12 col-lg-auto me-lg-3 mb-2 justify-content-center mb-md-0">
            {% if request.user.is_authenticated %}
                <div class="dropdown text-end">
                    <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
                    </a>
                    <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1" style="">
                        <li><a href="{% url 'Channels:Channel' channel_id=request.user.id %}" class="dropdown-item">Profile</a></li>
                        <li><a class="dropdown-item" href="#">New project...</a></li>
                        <li><a class="dropdown-item" href="#">Settings</a></li>
                        <li><a class="dropdown-item" href="#">Profile</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a href="{% url 'Users:logout' %}" class="dropdown-item">Logout</a></li>
                    </ul>
                </div>
            {% else %}
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="{% url 'Users:login' %}" class="nav-link px-2 link-secondary">login</a></li>
                </ul>
            {% endif %}
    </div>
</header>

{#<header>#}
{#    <div>#}
{#        {% if request.user.is_authenticated %}#}
{#            <a href={% url 'Users:logout' %}>logout</a>#}
{#            <a href={% url 'Channels:Channel' channel_id=request.user.id %}>Profile</a>#}
{#        {% else %}#}
{#            <a href={% url 'Users:login' %}>login</a>#}
{#        {% endif %}#}
{#        <a href={% url 'main:main' %}>Main Page</a>#}
{#    </div>#}
{#</header>#}
{% block body %} {% endblock body %}
</body>
<script type="text/javascript" src="{% static 'js/jquery-3.6.0.min.js' %}" ></script>
{% block scripts %}
{% endblock scripts %}
</html>