Channels/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:channel_id>/', views.channel, name="Channel"),
    path('subscribe/', views.subscribe, name="Subscribe"),
]

app_name = 'Channels'

HenTube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('Users.urls')),
    path('channels/', include('Channels.urls')),
    path('videos/', include('Videos.urls')),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Videos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:video_id>/', views.video, name='video'),
    path('upload_video/', views.upload_video, name='upload_video'),
    path('set_comment/', views.create_comment, name='set_comment'),
    path('react/', views.react, name='react'),
]

app_name = 'Videos'

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main_page, name='main'),
]

app_name = 'main'

Channels/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class ChannelTags(models.Model):
    value = models.TextField(max_length=20)


class Channels(models.Model):
    user = models.OneToOneField(
        User,
        primary_key=True,
        on_delete=models.CASCADE,
    )
    description = models.TextField(max_length=300, null=True, default=None)
    creation_date = models.DateTimeField("creation date", default=timezone.now)
    tags = models.ManyToManyField(ChannelTags, null=True)
    subscribers = models.BigIntegerField(default=0)

    def __str__(self):
        return f'id: {self.user_id}, creation date: {self.creation_date}'

    def add_subscriber(self, value):
        self.subscribers += value
        self.save()


class Subscriptions(models.Model):
    subscriber = models.ForeignKey(Channels, related_name='subscriber', on_delete=models.CASCADE)
    subscription = models.ForeignKey(Channels, related_name='subscription', on_delete=models.CASCADE)

    def __str__(self):
        return f"subscriber: {self.subscriber}, subscription: {self.subscription}"

Channels/views.py
from django.shortcuts import render
from .models import Channels, Subscriptions
from Videos.models import Videos
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse


def channel(request, channel_id):
    chan = Channels.objects.get(pk=channel_id)
    videos = Videos.objects.filter(publisher_id=channel_id).order_by('-pub_date')
    if channel_id != request.user.id:
        isSubscribed = bool(Subscriptions.objects.filter(
            subscriber_id=request.user.id,
            subscription_id=channel_id,
        ))
    else:
        isSubscribed = False
    return render(request, 'Channels/Index.html', {'channel': chan,
                                                   'videos': videos,
                                                   'isSubscribed': isSubscribed})


@login_required(login_url='Users:login')
def subscribe(request):
    if request.POST['value'] == 'true':
        Subscriptions.objects.filter(
            subscriber_id=int(request.POST['subscriber']),
            subscription_id=int(request.POST['subscription']),
        ).delete()
        Channels.objects.get(pk=int(request.POST['subscription'])).add_subscriber(-1)
        value = 'false'
    else:
        Subscriptions(
            subscriber_id=request.POST['subscriber'],
            subscription_id=request.POST['subscription'],
        ).save()
        Channels.objects.get(pk=int(request.POST['subscription'])).add_subscriber(1)
        value = 'true'
    return JsonResponse({'status': 200, 'value': value}, status=200)

templates/Channels/Index.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block meta %}
    <title>Channel Page</title>
    <link href="{% static 'Channels/css/index.css' %}" rel="stylesheet" type="text/css">
{% endblock meta %}

{% block body %}
<div style="display: flex">
    <div class="channel_name">
        <h3 class="h3">{{ channel.user.username}}</h3>
        <p class="smoll_text"><span id="num_subscribers">{{ channel.subscribers }}</span> subscribers</p>
    </div>
    <div>
        {% if channel.user_id != request.user.id %}
            {% if isSubscribed %}
                <button onclick="Subscribe('true')" class="subscribe_button true">Subscribe</button>
                <button onclick="Subscribe('false')" class="subscribe_button false" hidden>Subscribe</button>
            {% else %}
                <button onclick="Subscribe('true')" class="subscribe_button true" hidden>Subscribe</button>
                <button onclick="Subscribe('false')" class="subscribe_button false">Subscribe</button>
            {% endif %}
        {% endif %}
    </div>
</div>
<div class="videos-container">
    {% for video in videos %}
        <div class="video-container">
            <a href="{% url 'Videos:video' video_id=video.id %}">
                <div class="video">
                    <div class="preview-container">
                        <div class="preview">
                            <img src="../..{% get_media_prefix %}{{ video.preview_path }}" alt="none">
                        </div>
                        <div class="duration">12:13</div>
                    </div>
                    <div class="title">{{ video.title }}</div>
                    <div class="chanel">
                        <a href="{% url 'Channels:Channel' channel_id=video.publisher_id %}">{{ video.publisher.username }}</a>
                    </div>
                    <div class="views">{{ video.views }} views • {{ video.pub_date|naturaltime }}</div>
                </div>
            </a>
        </div>
    {% endfor %}
</div>
{% endblock body %}

{% block scripts %}
<script type="application/javascript">
    function Subscribe (isSubscribed){
        $.ajax({
            url: "{% url "Channels:Subscribe" %}",
            data: {
                "subscriber": {{ request.user.id }},
                "subscription": {{ channel.user.id }},
                "value": isSubscribed,
                "csrfmiddlewaretoken": "{{ csrf_token }}"
            },
            type: "POST",
            success: function (response){
                if (response.status === 200){
                    $("." + isSubscribed).attr("hidden", "hidden")
                    $("." + response['value']).removeAttr("hidden")
                    switch (response["value"]){
                        case "true":{
                            let nunber = $("#num_subscribers")
                            let v = nunber.text()
                            nunber.text(parseInt(v)+1)
                            break;
                        }
                        case "false":{
                            let nunber = $("#num_subscribers")
                            let v = nunber.text()
                            nunber.text(parseInt(v)-1)
                            break;
                        }
                    }
                }
            }
        })
    }
</script>
{% endblock scripts %}