HenTube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('Users.urls')),
    path('channels/', include('Channels.urls')),
    path('videos/', include('Videos.urls')),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('registration/', views.registration, name='registration'),
]

app_name = 'Users'

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main_page, name='main'),
]

app_name = 'main'

Users/models.py
from django.db import models

# Create your models here.

Users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta():
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

Users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import RegistrationForm
from Channels.models import Channels


@login_required(login_url='Users:login')
def index(request):
    return render(request, 'Users/index.html', {})


def login_user(request):
    if request.user.is_authenticated:
        return redirect('Users:index')
    if request.method == 'POST':
        login_form = AuthenticationForm(request, data=request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('Users:index')
    return render(request, 'Users/LoginPage.html', {})


@login_required(login_url='Users:login')
def logout_user(request):
    logout(request)
    return redirect('Users:login')


def registration(request):
    if request.user.is_authenticated:
        return redirect('Users:index')
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            Channels(user=new_user).save()
            return redirect('Users:login')
    else:
        form = RegistrationForm()
    return render(request, 'Users/Registration.html', {'form': form})

templates/Users/Index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Login Page</title>
{% endblock meta %}

{% block styles %}
    <style>
        body{
            width: 1200px;
            margin: 0 auto;
        }
    </style>
{% endblock styles %}

{% block body %}
    <h1>you are logged in</h1>
{% endblock body %}

templates/Users/LoginPage.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Login Page</title>
{% endblock meta %}

{% block styles %}
    <style>
        body{
            width: 1200px;
            margin: 0 auto;
        }
    </style>
{% endblock styles %}

{% block body %}
    <form method="post" action="{% url 'Users:login' %}">
    {% csrf_token %}
      <div class="form-group">
        <label for="exampleInputLogin1">Login</label>
        <input type="text" class="form-control" id="exampleInputLogin1" aria-describedby="emailHelp" placeholder="Enter login" name="username">
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name="password">
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock body %}

templates/Users/Registration.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Registration</title>
{% endblock meta %}

{% block body %}
    <h1>Registration</h1>
    <form method="post" action={% url 'Users:registration' %}>
        {% csrf_token %}
        {{ form }}
        <button type="submit">Register</button>
    </form>
{% endblock body %}